version: "3"

services:
  app1:
    container_name: app1
    image: nginx
    volumes:
      - ./app1/www:/usr/share/nginx/html

  app2:
    container_name: app2
    image: nginx
    volumes:
      - ./app2/www:/usr/share/nginx/html

  server:
    container_name: server
    image: nginx
    volumes:
      - ./app1/app1.conf:/etc/nginx/conf.d/app1.conf
      - ./app2/app2.conf:/etc/nginx/conf.d/app2.conf
    ports:
      - "8080:80"